# Generated by Django 2.1.5 on 2019-04-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0005_add_golfer_city_data_again'),
        ('golfer', '0004_add_golfer_city_data'),
    ]

    operations = [
    ]
